import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header";
import Provider from "./provider";
import "@mysten/dapp-kit/dist/index.css";
import { RetroGrid } from "@/components/magicui/retro-grid";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <RetroGrid />

          <Header />
          {children}
        </Provider>
      </body>
    </html>
  );
}
