import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header";
import Provider from "./provider";
import "@mysten/dapp-kit/dist/index.css";
import { RetroGrid } from "@/components/magicui/retro-grid";
import { Orbitron } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={orbitron.className}>
      <body>
        <Provider>
          <RetroGrid />

          <Header />
          {children}
        </Provider>
      </body>
    </html>
  );
}
